type: postgresql
version:
  postgresql: "18.1"
mode: standalone
cluster:
  imageName: "ghcr.io/cloudnative-pg/postgresql:18.1-202511170807-standard-trixie@sha256:241bef1b31190865cdb99ac47f22f34e8746d79135dee820643b63cb5a6fe653"
  imagePullPolicy: IfNotPresent
  storage:
    storageClass: "longhorn"
  walStorage:
    enabled: true
    storageClass: "longhorn"
  enableSuperuserAccess: false
