serviceAccounts:
  server:
    create: true
    name: "prometheus-svc"
server:
  image:
    repository: quay.io/prometheus/prometheus
    tag: "v3.8.0"
  ingress:
    enabled: true 
    ingressClassName: "traefik"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
      traefik.ingress.kubernetes.io/router.middlewares: mon-oauth2-proxy-errors@kubernetescrd,mon-oauth2-proxy-forwardauth@kubernetescrd
    hosts:
      - prom.bear.fyi
    path: /
    pathType: Prefix
    tls:
      - secretName: prometheus-tls
        hosts:
          - prom.bear.fyi
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    storageClass: "longhorn"
  replicaCount: 2
  statefulSet:
    enabled: true
alertmanager:
  enabled: true
  persistence:
    enabled: true
    storageClass: "longhorn"
    accessModes:
      - ReadWriteOnce
    size: 2Gi
